using Preql;

namespace Preql.Sample;

// Example entity class
public class User
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public int Age { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("��️ Preql Sample Application");
        Console.WriteLine("=============================\n");

        // Create a PreqlContext with PostgreSQL dialect
        var context = new PreqlContext(SqlDialect.PostgreSql);

        // Example 1: Using SqlTableAlias with Handler (Indexer approach)
        Console.WriteLine("Example 1: Using SqlTableAlias with Handler");
        var u = context.Alias<User>();
        int userId = 123;
        
        // This uses the PreqlSqlHandler automatically!
        PreqlSqlHandler handler = $"SELECT {u["Id"]}, {u["Name"]}, {u["Email"]} FROM {u} WHERE {u["Id"]} = {userId.AsValue()}";
        var (handlerSql, handlerParams) = handler.Build();
        
        Console.WriteLine($"SQL: {handlerSql}");
        Console.WriteLine($"Parameters: {FormatParamList(handlerParams)}");
        Console.WriteLine();

        // Example 2: Complex Query with Handler
        Console.WriteLine("Example 2: Complex Query with Handler");
        string searchName = "%Smith%";
        int minAge = 30;
        
        PreqlSqlHandler handler2 = $"""
            SELECT {u["Id"]}, {u["Name"]}, {u["Email"]}, {u["Age"]}
            FROM {u}
            WHERE {u["Name"]} LIKE {searchName.AsValue()}
            AND {u["Age"]} >= {minAge.AsValue()}
            ORDER BY {u["Name"]}
            """;
        var (complexSql, complexParams) = handler2.Build();
        
        Console.WriteLine($"SQL: {complexSql}");
        Console.WriteLine($"Parameters: {FormatParamList(complexParams)}");
        Console.WriteLine();

        // Example 3: Building FormattableString for EF Core
        Console.WriteLine("Example 3: Building FormattableString for EF Core");
        PreqlSqlHandler handler3 = $"SELECT {u["Id"]}, {u["Name"]} FROM {u} WHERE {u["Id"]} = {userId.AsValue()}";
        var efCoreCompatible = handler3.BuildFormattable();
        
        Console.WriteLine($"FormattableString Format: {efCoreCompatible.Format}");
        Console.WriteLine($"Arguments: {FormatFormattableStringArgs(efCoreCompatible)}");
        Console.WriteLine($"Can be used with: context.Users.FromInterpolatedSql(...)");
        Console.WriteLine();

        // Example 4: Using GENERATED AliasProxy (Typed properties)
        Console.WriteLine("=============================");
        Console.WriteLine("Example 4: Using Generated AliasProxy");
        Console.WriteLine("(Typed Properties - Full IntelliSense!)");
        Console.WriteLine("=============================\n");

        var userProxy = new Preql.Sample.Generated.UserAliasProxy(context.Dialect);
        int searchId = 999;
        
        PreqlSqlHandler handler4 = $"SELECT {userProxy.Id}, {userProxy.Name}, {userProxy.Email} FROM {userProxy} WHERE {userProxy.Id} = {searchId.AsValue()}";
        var (proxySql, proxyParams) = handler4.Build();
        
        Console.WriteLine($"SQL: {proxySql}");
        Console.WriteLine($"Parameters: {FormatParamList(proxyParams)}");
        Console.WriteLine();
        Console.WriteLine("✨ Notice: Properties like 'userProxy.Id' instead of u[\"Id\"]!");
        Console.WriteLine("✨ This provides full IntelliSense and compile-time safety!");
        Console.WriteLine("✨ Generated by source generator - NO runtime reflection!");
        Console.WriteLine();

        // Example 5: Multiple Conditions
        Console.WriteLine("Example 5: Multiple Conditions");
        var user = context.Alias<User>();
        
        PreqlSqlHandler handler5 = $"""
            SELECT {user["Id"]}, {user["Name"]}, {user["Email"]}, {user["Age"]}
            FROM {user}
            WHERE {user["Age"]} >= {25.AsValue()}
            AND {user["Email"]} LIKE {"%.com".AsValue()}
            ORDER BY {user["Age"]} DESC
            """;
        var (multiSql, multiParams) = handler5.Build();
        
        Console.WriteLine($"SQL: {multiSql}");
        Console.WriteLine($"Parameters: {FormatParamList(multiParams)}");
        Console.WriteLine();

        Console.WriteLine("✅ All examples completed successfully!");
        Console.WriteLine("\n📝 Preql - Zero Reflection SQL Generation:");
        Console.WriteLine("  • ZERO runtime reflection");
        Console.WriteLine("  • ZERO runtime overhead");  
        Console.WriteLine("  • All work done by the C# compiler at build time");
        Console.WriteLine("  • Type-safe column and table references");
        Console.WriteLine("  • Compatible with EF Core via BuildFormattable()");
        Console.WriteLine("\n🎯 Usage:");
        Console.WriteLine("  var u = context.Alias<User>();");
        Console.WriteLine("  PreqlSqlHandler h = $\"SELECT {u[\"Id\"]} FROM {u} WHERE {u[\"Id\"]} = {id.AsValue()}\";");
        Console.WriteLine("  var (sql, params) = h.Build();");
        Console.WriteLine("\n💡 Or with generated proxy:");
        Console.WriteLine("  var u = new UserAliasProxy(dialect);");
        Console.WriteLine("  PreqlSqlHandler h = $\"SELECT {u.Id} FROM {u} WHERE {u.Id} = {id.AsValue()}\";");
    }

    static string FormatFormattableStringArgs(FormattableString fs)
    {
        var args = fs.GetArguments();
        if (args.Length == 0)
            return "none";

        return string.Join(", ", args.Select((arg, i) => $"[{i}]={arg}"));
    }

    static string FormatParamList(IReadOnlyList<object?> parameters)
    {
        if (parameters == null || parameters.Count == 0)
            return "none";

        return string.Join(", ", parameters.Select((p, i) => $"@p{i}={p}"));
    }
}
